{% set version = "0.9.0" %}

package:
  name: parsimonious
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/parsimonious/parsimonious-{{ version }}.tar.gz
  sha256: b2ad1ae63a2f65bd78f5e0a8ac510a98f3607a43f1db2a8d46636a5d9e4a30c1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six >=1.9.0

test:
  imports:
    - parsimonious
  commands:
    - python -m nose -s -v parsimonious -e test_benchmarks
  requires:
    - nose

about:
  home: https://github.com/erikrose/parsimonious/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: (Soon to be) the fastest pure-Python PEG parser I could muster
  description: (Soon to be) the fastest pure-Python PEG parser I could muster
  doc_url: https://github.com/erikrose/parsimonious/
  dev_url: https://github.com/erikrose/parsimonious/

extra:
  recipe-maintainers:
    - nelson-liu
